# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  backend-lint:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: node:lts
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      - run: 
          command: npm install

      - run:
          name: "Backend lint"
          command: npm run lint-check
          working_directory: backend
    
  backend-type-check :
    docker:
      - image: node:lts
    
    steps:
      - checkout

      - run: 
          command: npm install

      - run: 
          command: npm run db-install
          working_directory: backend
      
      - run: 
          command: npm run type-check
          working_directory: backend

  backend-unit-tests:
    docker:
      - image: node:lts
    
    steps:
      - checkout

      - run: 
          command: npm install

      - run: 
          command: npm run db-install
          working_directory: backend
      
      - run: 
          command: npm run unit-tests
          working_directory: backend

  release:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: 
          command: npm install
      - run:
          name: "Semantic Release"
          command: npm run semantic-release

  build_and_deploy:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: 
          command: npm install
      - run:
          name: "Build Backend"
          command: |
              npm run build
              npm run db-install
          working_directory: backend
        
      - run:
          name: "Build Frontend"
          command: npm run build
          working_directory: frontend
      




# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  backend-ci-workflow:
    jobs:
      - backend-lint
      - backend-type-check
      - backend-unit-tests

  cd-workflow:
    jobs:
      - backend-lint:
          filters:
            branches:
              only:
                - main
      - backend-type-check:
          filters:
            branches:
              only:
                - main
      - backend-unit-tests:
          filters:
            branches:
              only:
                - main
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
      - release:
          filters:
            branches:
              only:
                - main


      


